module.exports = [
  "Design a smart thermostat system",
  "Design a URL shortening service",
  "Design a news feed system",
  "Design a secure credit card transaction system",
  "Design a fraud detection system for real-time transactions",
  "Design a personal finance dashboard",
  "Design a banking API service for third-party developers",
  "Design a rate limiter for a public API",
  "Design a system for sending OTP via SMS and email",
  "Design a document upload and verification system",
  "Design a money transfer service",
  "Design a ledger system to track account balances and transactions",
  "Design a distributed job scheduler",
  "Design a secure login system with multi-factor authentication",
  "Design a transaction search and filtering system",
  "Design a secure and auditable logging system",
  "Design an alert system for suspicious activity",
  "Design a chatbot assistant for customer support",
  "Design an internal developer portal for microservices",
  "Design a secure token-based authentication service",
  "Design a customer support ticketing system",
  "Design a file storage service for secure document access",
  "Design a system to reconcile financial transactions",
  "Design a video streaming service",
  "Design a messaging system",
  "Design a distributed cache system",
  "Design a recommendation engine",
  "Design a ride-sharing service",
  "Design a search autocomplete system",
  "Design a social media platform",
  "Design a scalable notification system",
  "Design a load balancer",
  "Design a real-time collaboration tool (like Google Docs)",
  "Design an e-commerce checkout system",
  "Design an API rate-limiting middleware",
  "Design a content delivery network (CDN)",
  "Design a web crawler",
  "Design a leaderboard system with real-time updates",
  "Design a feature flag service",
  "Design a job queue system with retry logic",
  "Design a metrics collection and monitoring system"
];
